services:
  coeiroink_api:
    build: ./coeiroink_api
    restart: always
    volumes:
      - ./coeiroink_api/speaker_info:/app/COEIROINK_LINUX/speaker_info

  style_bert_vits2_api:
    build: ./style_bert_vits2_api
    restart: always
    volumes:
      - ./style_bert_vits2_api/model_assets:/app/model_assets

  bot:
    build: ./bot
    volumes:
      - ./bot:/app
    env_file:
      - .env
    depends_on:
      - api
    restart: always
