services:
  bot:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - ..:/workspace

  coeiroink_api:
    build: ../coeiroink_api
    volumes:
      - ../coeiroink_api/speaker_info:/app/COEIROINK_LINUX/speaker_info
    restart: always
    ports:
      - "8080:80"
    platform: linux/amd64

  style_bert_vits2_api:
    build: ../style_bert_vits2_api
    restart: always
    volumes:
      - ../style_bert_vits2_api/model_assets:/app/model_assets
    ports:
      - "8081:5000"
    platform: linux/amd64

  web:
    build: ../web
    restart: always
    ports:
      - "8082:8000"
    volumes:
      - ../web/app:/app
